# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromatogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Column', models.TextField()),
                ('Datetime', models.FloatField()),
                ('Flow', models.TextField()),
                ('UVWavelength', models.TextField()),
                ('Sample', models.TextField()),
                ('InjectionVolume', models.TextField()),
                ('Concentration', models.TextField()),
                ('Comment', models.TextField()),
                ('AcquireADC', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Eluent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chromatogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Chromatogram')),
            ],
        ),
        migrations.CreateModel(
            name='HplcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelName', models.TextField()),
                ('Datetime', models.FloatField()),
                ('Value', models.FloatField()),
                ('Chromatogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Chromatogram')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Percentage', models.FloatField()),
                ('Eluent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Eluent')),
            ],
        ),
    ]
