# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-23 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='DeadTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
