# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0002_chromatogram_deadtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
                ('Chromatogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Chromatogram')),
            ],
        ),
    ]
