# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0003_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='ChannelName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
