# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0005_chromatogram_factorsunits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelName', models.TextField(max_length=2048)),
                ('Datetime', models.IntegerField()),
                ('Value', models.FloatField()),
                ('Chromatogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Chromatogram')),
            ],
        ),
    ]
