# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-07-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0006_baseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseline',
            name='Datetime',
        ),
        migrations.RemoveField(
            model_name='baseline',
            name='Value',
        ),
        migrations.AddField(
            model_name='baseline',
            name='DatetimeValue',
            field=models.TextField(default=(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseline',
            name='Type',
            field=models.TextField(default='linear'),
            preserve_default=False,
        ),
    ]
