# Generated by Django 2.0.1 on 2018-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0007_auto_20170711_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hplcdata',
            name='ChannelName',
            field=models.CharField(max_length=255, db_index=True),
        ),
        migrations.AlterField(
            model_name='hplcdata',
            name='Datetime',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hplcdata',
            name='Value',
            field=models.FloatField(db_index=True),
        ),
    ]
