# Generated by Django 2.0.1 on 2018-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0008_auto_20180124_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='Name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
