# Generated by Django 2.0.1 on 2018-02-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0009_peak_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='MaxRuntime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
