# Generated by Django 2.0.1 on 2018-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0011_chromatogram_rheodyneswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='ConcentrationUnit',
            field=models.TextField(default='mg/ml'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chromatogram',
            name='SampleRate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
