# Generated by Django 2.0.1 on 2018-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0012_auto_20180222_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='NextChromatogram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
