# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0013_chromatogram_nextchromatogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='ChannelOrderShift',
            field=models.TextField(default='UV - 0,Counter - 30'),
            preserve_default=False,
        ),
    ]
