# Generated by Django 2.0.1 on 2018-05-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0014_chromatogram_channelordershift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chromatogram',
            options={'permissions': (('chromatogram_edit', 'Can edit a chromatograms data'), ('chromatogram_start', 'Can start a chromatogram'), ('chromatogram_can_stop_others', 'Can stop a chromatogram started by another user'), ('chromatogram_delete', 'Can delete a chromatogram and all of its data'))},
        ),
        migrations.AlterField(
            model_name='baseline',
            name='ChannelName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hplcdata',
            name='ChannelName',
            field=models.TextField(db_index=True),
        ),
    ]
