# Generated by Django 2.0.5 on 2018-05-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0014_chromatogram_channelordershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='ChannelName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hplcdata',
            name='ChannelName',
            field=models.TextField(db_index=True),
        ),
    ]
