# Generated by Django 2.0.5 on 2018-05-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0015_auto_20180516_0443'),
        ('JuHPLC', '0015_auto_20180509_0740'),
    ]

    operations = [
    ]
