# Generated by Django 2.0.1 on 2018-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0016_merge_20180516_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatogram',
            name='HalfLife',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
