# Generated by Django 2.0.1 on 2018-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0017_chromatogram_halflife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromatogram',
            name='HalfLife',
            field=models.FloatField(),
        ),
    ]
