# Generated by Django 2.0.1 on 2018-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0019_calibration_jsonjuhplcchromatogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Channel',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Column',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Eluent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Flow',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='RetentionFactor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='RetentionFactorError',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Slope',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='UVWaveLength',
            field=models.FloatField(default=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='Unit',
            field=models.TextField(default='g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='YAxisIntercept',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
