# Generated by Django 2.1.2 on 2018-12-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuHPLC', '0020_auto_20180814_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField()),
                ('Text', models.TextField()),
                ('Chromatogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuHPLC.Chromatogram')),
            ],
        ),
    ]
